-- Generated by scripts/new-migration.mjs from `prisma migrate diff`.
-- 5 statement block(s) targeting the listing_fts search index were
-- removed: Prisma cannot see virtual tables and always proposes dropping them.

-- AlterTable
ALTER TABLE "Listing" ADD COLUMN "propertyOwnerName" TEXT;
ALTER TABLE "Listing" ADD COLUMN "propertyOwnerNote" TEXT;
ALTER TABLE "Listing" ADD COLUMN "propertyOwnerPhone" TEXT;
